### ISSUE TITLE
Could not pass Entity explode event

### ISSUE THREAD

**Issue by DrkMatr1984** [Phiwa/DragonTravel#42]
http://pastebin.com/bzvg78zd
on TnT explode

06.02 03:34:14 [Server] INFO Caused by: java.lang.NoClassDefFoundError: eu/phiwa/dragontravel/nms/v1_8_R3/RyeDragon

Seems we need to implement some sort of reflection here to prevent this error in the future.
I've implemented a temporary workaround for this issue by first checking if the entity exploding is an instanceof EnderDragon.

**Comment by Phiwa** [comment]
Thanks for the fix, the problem never occured for me since I never used TNT while testing DT... ;)

**Comment by DrkMatr1984** [comment]
I figured. If you're not exploding much, the entity explode event would never get called. I believe in order to have this work with versions other than 1.8 R3 we'll have to implement reflection instead of importing RyeDragon from eu.phiwa.dragontravel.nms.v1_8_R3.RyeDragon outright.

**Comment by Phiwa** [comment]
Yes, I saw it  already. I guess,  that will be included in a third "nms-specific" class...
Maybe it is a good idea to reopen this issue to keep track of the process.

**Comment by DrkMatr1984** [comment]
Yeah, keep it open for now. One of us will get to it soon :)
